import { NextRequest, NextResponse } from 'next/server';
import { pinata } from '../../../lib/pinataconfig';

interface FPLManager {
  entry: number;
  entry_name: string;
  player_name: string;
  total: number;
  event_total: number;
  rank: number;
  fid?: number;
  username?: string;
}

interface InfographicData {
  top3: FPLManager[];
  bottom3: FPLManager[];
  weekWinners: FPLManager[];
  totalManagers: number;
  gameWeek: number;
  leagueName: string;
}

// Simple SVG infographic generator
function generateInfographicSVG(data: InfographicData): string {
  const { top3, bottom3, weekWinners, totalManagers, gameWeek, leagueName } = data;
  
  const svg = `
    <svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bgGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#1a1a2e;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#16213e;stop-opacity:1" />
        </linearGradient>
        <linearGradient id="goldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#ffd700;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#ffed4e;stop-opacity:1" />
        </linearGradient>
        <linearGradient id="silverGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#c0c0c0;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#e5e5e5;stop-opacity:1" />
        </linearGradient>
        <linearGradient id="bronzeGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#cd7f32;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#daa520;stop-opacity:1" />
        </linearGradient>
      </defs>
      
      <!-- Background -->
      <rect width="800" height="600" fill="url(#bgGradient)"/>
      
      <!-- Header -->
      <text x="400" y="40" text-anchor="middle" fill="#ffffff" font-family="Arial, sans-serif" font-size="24" font-weight="bold">
        ${leagueName} - Game Week ${gameWeek}
      </text>
      
      <!-- Top 3 Section -->
      <text x="400" y="80" text-anchor="middle" fill="#ffd700" font-family="Arial, sans-serif" font-size="20" font-weight="bold">
        🏆 Top 3 Overall
      </text>
      
      ${top3.map((manager, index) => {
        const y = 120 + (index * 60);
        const medal = index === 0 ? '🥇' : index === 1 ? '🥈' : '🥉';
        const gradient = index === 0 ? 'goldGradient' : index === 1 ? 'silverGradient' : 'bronzeGradient';
        return `
          <rect x="50" y="${y-10}" width="300" height="50" rx="10" fill="url(#${gradient})" opacity="0.8"/>
          <text x="70" y="${y+10}" fill="#000000" font-family="Arial, sans-serif" font-size="16" font-weight="bold">
            ${medal} @${manager.username}
          </text>
          <text x="70" y="${y+30}" fill="#000000" font-family="Arial, sans-serif" font-size="14">
            ${manager.total}pts | Rank #${manager.rank}
          </text>
        `;
      }).join('')}
      
      <!-- Week Winners Section -->
      <text x="400" y="320" text-anchor="middle" fill="#00ff88" font-family="Arial, sans-serif" font-size="20" font-weight="bold">
        ⭐ Week Winners
      </text>
      
      ${weekWinners.map((manager, index) => {
        const y = 360 + (index * 60);
        const medal = index === 0 ? '🥇' : index === 1 ? '🥈' : '🥉';
        return `
          <rect x="450" y="${y-10}" width="300" height="50" rx="10" fill="#00ff88" opacity="0.8"/>
          <text x="470" y="${y+10}" fill="#000000" font-family="Arial, sans-serif" font-size="16" font-weight="bold">
            ${medal} @${manager.username}
          </text>
          <text x="470" y="${y+30}" fill="#000000" font-family="Arial, sans-serif" font-size="14">
            ${manager.event_total}pts this week
          </text>
        `;
      }).join('')}
      
      <!-- Bottom 3 Section -->
      <text x="400" y="520" text-anchor="middle" fill="#ff6b6b" font-family="Arial, sans-serif" font-size="16" font-weight="bold">
        😅 Bottom 3 | Total Managers: ${totalManagers}
      </text>
      
      ${bottom3.map((manager, index) => {
        const y = 550 + (index * 25);
        return `
          <text x="50" y="${y}" fill="#ffffff" font-family="Arial, sans-serif" font-size="12">
            ${bottom3.length - index}. @${manager.username} - ${manager.total}pts
          </text>
        `;
      }).join('')}
      
      <!-- Footer -->
      <text x="400" y="580" text-anchor="middle" fill="#888888" font-family="Arial, sans-serif" font-size="12">
        Generated by FC Footy App ⚽️
      </text>
    </svg>
  `;
  
  return svg;
}

export async function POST(req: NextRequest) {
  try {
    const { fplData, gameWeek = 1, leagueName = "Farcaster Fantasy League" } = await req.json();
    
    console.log('🔍 Debug: Infographic API received:', {
      fplDataCount: fplData?.length || 0,
      gameWeek,
      leagueName,
      sampleData: fplData?.slice(0, 2) || []
    });
    
    if (!fplData || !Array.isArray(fplData)) {
      return NextResponse.json({ error: 'Invalid FPL data provided' }, { status: 400 });
    }

    // Process the data to get top/bottom performers
    const managersWithFIDs = fplData.filter((manager: FPLManager) => manager.username);
    const sortedByTotal = [...managersWithFIDs].sort((a, b) => b.total - a.total);
    const sortedByEventTotal = [...managersWithFIDs].sort((a, b) => b.event_total - a.event_total);

    console.log('🔍 Debug: Processed infographic data:', {
      totalFplData: fplData.length,
      managersWithFIDs: managersWithFIDs.length,
      top3Count: sortedByTotal.slice(0, 3).length,
      bottom3Count: sortedByTotal.slice(-3).length,
      weekWinnersCount: sortedByEventTotal.slice(0, 3).length
    });

    const infographicData: InfographicData = {
      top3: sortedByTotal.slice(0, 3),
      bottom3: sortedByTotal.slice(-3),
      weekWinners: sortedByEventTotal.slice(0, 3),
      totalManagers: fplData.length,
      gameWeek,
      leagueName
    };

    // Generate SVG infographic
    const svgContent = generateInfographicSVG(infographicData);
    
    // Convert SVG to buffer
    const buffer = Buffer.from(svgContent, 'utf-8');
    
    // Create file for upload
    const file = new File([buffer], `gameweek-${gameWeek}-summary.svg`, { type: 'image/svg+xml' });

    // Check if Pinata is configured
    const pinataJwt = process.env.NEXT_PUBLIC_PINATAJWT || process.env.PINATA_JWT;
    if (!pinataJwt) {
      return NextResponse.json({ 
        error: 'Pinata JWT not configured. Please set NEXT_PUBLIC_PINATAJWT environment variable.',
        svgContent // Return SVG content for manual upload
      }, { status: 500 });
    }

    // Upload to IPFS via Pinata
    const result = await pinata.upload.file(file);
    
    const gateway = process.env.NEXT_PUBLIC_PINATAGATEWAY || process.env.PINATA_GATEWAY || 'https://gateway.pinata.cloud';
    const ipfsUrl = `${gateway}/ipfs/${result.IpfsHash}`;
    
    return NextResponse.json({ 
      success: true,
      ipfsHash: result.IpfsHash,
      ipfsUrl,
      svgContent // Also return SVG content for debugging
    });

  } catch (error) {
    console.error('Infographic generation failed:', error);
    return NextResponse.json({ 
      error: 'Failed to generate infographic',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}
